import { Header } from '@/components'
import '../styles/globals.css'
import Providers from './providers'

export const metadata = {
  title: 'Custom Sports',
  description: 'Generated by create next app'
}

interface Props {
  children: React.ReactNode
}

async function RootLayout({ children }: Props) {
  return (
    <html lang='en'>
      <body>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  )
}

export default RootLayout
